return {
    Version = "1.04", -- Change this to the version of your script
    News = { 
        '<b><font color="rgb(255,0,0)">V 1.06</font></b>',
        '> Improved the auto-join system (if you found a bug please report in discord).',
        '<b><font color="rgb(255,0,0)">V 1.05</font></b>',
        '> Made paid script execute much faster.',
        '> Fixed auto level does not work when you finish speed raid .',
         '<b><font color="rgb(255,0,0)">V 1.04</font></b>',
        '> Fixed all webhooks.',
        '> Fixed auto swap does not work after speed raid .',
        '> Fixed Discord auto join .',
        '> Added new executor suggestion .',
        '<b><font color="rgb(255,0,0)">V 1.03</font></b>',
        '> Added New Skill Method for Hydrogen mac version because it does not support the current auto skill.',
        '<b><font color="rgb(255,0,0)">V 1.02</font></b>',
        '> Added new map to the auto level.',
        '> Added Select skills Option for paid .',
         '<b><font color="rgb(255,0,0)">V 1.01</font></b>',
        '> Fixed mobile UI version.',
        '> Fixed Black Screen .',
        '> Fixed Hide/Minimize UI.',
         '<b><font color="rgb(255,0,0)">V 1</font></b>',
        '> The Update may have bugs please Report and I will fix it  .',
        '> New UI Desingne With a lot of things .',
        '> Improved the script and fixed a lot of bugs.',
        '> Added New Ui for mobile users.',
        '> Added New Tab Layout you can change it in credits tab.',
        '> Added New KeyBord Script for mobile users.',
        '> Made the script friendly for those who dont know how to use it (Suggest anything and I will add it to make it more easily).',
        '> I have added a lot more but I dont remember, find it by yourself .',
        '<b><font color="rgb(255,0,0)">V 0.4</font></b>',
        '> Fixed Farm AFK.',
        '<b><font color="rgb(255,0,0)">V 0.5</font></b>',
        '> Improved Paid Auto Dodge its much faster and safe.',
        '> Added Custom setting for FPS Cap.',
        '> Added a button to show the update logs.',
        '<b><font color="rgb(255,0,0)">V 0.4</font></b>',
        '> Fixed Farm AFK.',
        '<b><font color="rgb(255,0,0)">V 0.3</font></b>',
        '> New Change Log UI.',
        '> Linkvertise now has 6 steps.',
        '> New server.',
        '> Fixed Auto upgrade/equip best cards.',
        '> Fixed auto upgrade webhook.',
        '> Added new checks to prevent the script from crashing.',
        '<b><font color="rgb(255,0,0)">V 0.2</font></b>',
        '> New AI Suggestions: Get helpful messages on Discord to improve your gameplay and become better at the game.',
        '> Free Auto Dodge Update: Apologies, but the auto dodge will stop working after 4 hours. You ll need to get a new key to make it work again. If the auto dodge expires, the TP Behind feature will activate automatically.',
        '> Updated Select Raid and Dimension: Now you can choose them whenever you want.',
        '> Ive made many improvements and fixed bugs and everything above.',
        '<b><font color="rgb(255,0,0)">V 0.1</font></b>',
        '> Updated the wishlist System',
        '> Fixed Auto Dodge',
        '> New Auto Delete mass cards',
        '> New Auto Upgrade Cards',
        '> New auto Equip best cards with some advance stats',
        '> Webhook for Upgrade, Delete, Equip cards',
        '> Removed Prem Tab',
        '> New Reset Webhook id',
        '> New reset setting in the credit tab it will show when the script load',
        '> New hide UI / Minimize ui',
        '> New Auto leave',
    },
    Title = 'The Intruders',
    MainText = 'Make Sure to join our <b>Discord Server</b>.<br/><font color="rgb(0,155,225)">https://discord.gg/vfkD5VCRKU</font>',
    DelayToDestroy = 60,
    From = 'ToZxart', 
}
