return {
    Version = "1.08", -- Change this to the version of your script
    News = { 
         'V 1.08',
        '> Added The New Version of the script.',
        '> Added Auto Fruit 1 and 2 with 2 methods.',
        '> Added Auto Raid Challange .',
        '> Added New Map to the auto level (I will make it automatic later) .',
        '> I will fix the raid challenge webhook later.',
        '> script now back to paid plan and free version too using linkvertise.',
         'V 1.07',
        '> Added Auto Madoki.',
        '> Webhooks now works better and it will give you more info and it will mention you when you get rare stuff.',
        '> Improved the load time of the script.',
        '> Improved the auto dodge it is now much faster and should not fall.',
        '> Key UI now has buttons.',
        '> Officially closed the free script.',
        '> AI farm soon if I get some new buyers.',
        'V 1.06',
        '> Improved the auto-join system (if you found a bug please report in discord).',
        'V 1.05',
        '> Made paid script execute much faster.',
        '> Fixed auto level does not work when you finish speed raid .',
         'V 1.04',
        '> Fixed all webhooks.',
        '> Fixed auto swap does not work after speed raid .',
        '> Fixed Discord auto join .',
        '> Added new executor suggestion .',
        'V 1.03',
        '> Added New Skill Method for Hydrogen mac version because it does not support the current auto skill.',
        'V 1.02',
        '> Added new map to the auto level.',
        '> Added Select skills Option for paid .',
         'V 1.01',
        '> Fixed mobile UI version.',
        '> Fixed Black Screen .',
        '> Fixed Hide/Minimize UI.',
         'V 1',
        '> The Update may have bugs please Report and I will fix it  .',
        '> New UI Desingne With a lot of things .',
        '> Improved the script and fixed a lot of bugs.',
        '> Added New Ui for mobile users.',
        '> Added New Tab Layout you can change it in credits tab.',
        '> Added New KeyBord Script for mobile users.',
        '> Made the script friendly for those who dont know how to use it (Suggest anything and I will add it to make it more easily).',
        '> I have added a lot more but I dont remember, find it by yourself .',
        'V 0.4',
        '> Fixed Farm AFK.',
        'V 0.5',
        '> Improved Paid Auto Dodge its much faster and safe.',
        '> Added Custom setting for FPS Cap.',
        '> Added a button to show the update logs.',
        'V 0.4',
        '> Fixed Farm AFK.',
        'V 0.3',
        '> New Change Log UI.',
        '> Linkvertise now has 6 steps.',
        '> New server.',
        '> Fixed Auto upgrade/equip best cards.',
        '> Fixed auto upgrade webhook.',
        '> Added new checks to prevent the script from crashing.',
        'V 0.2',
        '> New AI Suggestions: Get helpful messages on Discord to improve your gameplay and become better at the game.',
        '> Free Auto Dodge Update: Apologies, but the auto dodge will stop working after 4 hours. You ll need to get a new key to make it work again. If the auto dodge expires, the TP Behind feature will activate automatically.',
        '> Updated Select Raid and Dimension: Now you can choose them whenever you want.',
        '> Ive made many improvements and fixed bugs and everything above.',
        'V 0.1',
        '> Updated the wishlist System',
        '> Fixed Auto Dodge',
        '> New Auto Delete mass cards',
        '> New Auto Upgrade Cards',
        '> New auto Equip best cards with some advance stats',
        '> Webhook for Upgrade, Delete, Equip cards',
        '> Removed Prem Tab',
        '> New Reset Webhook id',
        '> New reset setting in the credit tab it will show when the script load',
        '> New hide UI / Minimize ui',
        '> New Auto leave',
    },
    Title = 'The Intruders',
    MainText = 'Make Sure to join our <b>Discord Server</b>.<br/><font color="rgb(0,155,225)">https://discord.gg/vfkD5VCRKU</font>',
    DelayToDestroy = 15,
    From = 'ToZxart', 
}
