return {
  Version = "1.17",
  News = {
     "V 1.17 - 9/23/2025",
    "> Rewrote the join system for improved performance",
    "> Fixed dungeon issue where it sometimes failed.",
    "Report any errors ASAP so I can fix them quickly.",
    "V 1.16 - 9/18/2025",
    "> Added: Auto Rejoin toggle and Rejoin Time slider (30m to 3h).",
    "> Added: auto redeem codes feature.",
    "> Some improvements to prevent stuck issues.",
    "V 1.15 - 9/17/2025",
    "> Fixed: auto-upgrade, auto-gacha, and auto-progression (fully stable now).",
    "> Fixed: auto-hatch (works properly) + added auto-hatch delay option.",
    "> Reworked the auto farm - now you can select multiple options to farm.",
    "> Smarter dropdowns—only display content from worlds you've unlocked.",
    "> Updated auto-raid—shows raids only from unlocked worlds.",
    "> Added: anti-public server protection (prevents reports or mutes when kicked and script restarts).",
    "> Fixed: dungeon webhook bug.",
    "> Added: raid webhook.",
    "> Fixed: dropdown rarity displaying incorrect info.",
    
    "V 1.14 - 9/13/2025",
    "> Fixed and improved teleportation system for smoother mob farming.",
    "> Resolved dungeon-related issues and bugs.",
    "> Auto buff system fully stabilized and should now work consistently.",
    "> Overall system stability improvements.",
    
    "V 1.13 - 9/12/2025",
    "> Fixed long-term farming lag for smoother performance.",
    "> Resolved mob detection issue (new mechanism added to handle loading delays automatically).",
    "> Auto buffs are now global and work across all areas.",
    "> Auto stats fully fixed and stable.",
    "> Added a new gacha feature to enhance gameplay.",
    "V 1.13 - 9/11/2025",
    "> Joining system fixed—should now function smoothly.",
    "> Titan defense raid, and related issues resolved.",
    "> Script optimized for better performance (lag significantly reduced).",
    "> Auto buff added (currently in beta; expected to work but may need further adjustments).",
    "> Some minor bugs remain, which will be patched in upcoming updates.",
    "V 1.13 - 9/10/2025",
    "> Fixed auto-leaf raid bug.",
    "> New dropdown menu to choose which world to auto hatch.",
    "> Auto-delete weapons + auto-equip best weapon.",
    "> World auto-detection accuracy improved / teleport issues in current world fixed.",
    "> Smarter moderator detection, with webhook alerts (if webhook URL is set).",
    "> Added auto-block to prevent joining raids from locked worlds.",
    "> Auto gacha, upgrade, and progression systems added.",
    "> Added auto chest collection.",
    "> Gacha Systems: Swords, Pirate Crew, Dragon Race, Saiyan Evolution, Reiatsu Color, Curses, Demon Arts, Solo Hunter Rank, Grimoire, Power Eyes.",
    "> Upgrade Systems: Spiritual Pressure, Curse Progression, Monarch Progression, ReAwakening Progression, Fire Spirit Progression, Attack Range II, Chakra Progression, Spiritual Upgrade.",
    "> Progression Systems: Lucky Spirit.",
    "V 1.12 - 9/07/2025",
    "> All features are now FREE for everyone!",
    "V 1.11 - 3/29/2024",
    "> Fixed Auto Swap Team.",
    "V 1.10 - 3/29/2024",
    "> Fixed Auto Dodge stop working in the last map(hope so :).",
    "> Fixed user info webhook show wrong informations.",
    "> Fixed UI issue that makes some executors does not work.",
    "V 1.09 - 3/28/2024",
    "> Added Hide Button For Mobile Users.",
    "> Improvet the GUI.",
    "> Improvet Auto Fruit.",
    "V 1.08 - 3/24/2024",
    "> Added The New Version of the script.",
    "> Added Auto Fruit 1 and 2 with 2 methods.",
    "> Added Auto Raid Challenge.",
    "> Added New Map to the auto level (I will make it automatic later).",
    "> I will fix the raid challenge webhook later.",
    "> script now back to a paid plan and free version to using linkvertise."
  },
  Title = "The Intruders",
  MainText = "Make Sure to join our <b>Discord Server</b>.<br/><font color=\"rgb(0,155,225)\">https://discord.gg/vfkD5VCRKU</font><br/><br/>Latest updates include major performance improvements, new gacha systems, and enhanced auto-farming features!",
  DelayToDestroy = 15,
  From = "ToZxart"
}
