return {
  Version = "1.16",
  News = {
    "V 1.16 - 10/07/2025",
    "> Fixed auto mine issues",
    "> Updated auto mine: when teleport is selected, it now uses Tween teleport (the old teleport was detected by the game, causing errors over time)",
    "> Added Tween service for smoother movement",
    "> Introduced 'Ores per Room' — select how many ores to farm before moving to the next room",
    "> Added ore timeout setting",
    "> Added customizable auto speed — adjust MoveTo speed from the main tab for both Tween and MoveTo modes",
    "> Added auto rebirth feature",
    "> Reworked auto dungeon system",
    "V 1.15 - 9/16/2025",
    "> Resolved game GUI not opening bug.",
    "> Fixed auto tree feature.",
    "> :star: Fixed auto collect falling stars.",
    "> Fixed auto hatch issue for season events.",
    "> Fixed Auto Mining.",
    "V 1.14 - 9/16/2025",
    "> Added Auto Farm Metero .",
    "> Added Auto Buy Merchant .",
    "> Added Auto Collect Orbs feature.",
    "> Added Auto Collect Falling Stars.",
    "> Complete integration achieved between all automation systems (Auto Mine, Auto Metero, Auto Dungeon, and Auto Tree).",
    "> Please report any bugs through our Discord server. Additional features in development.",
  },
  Title = "The Intruders",
  MainText = "Make Sure to join our <b>Discord Server</b>.<br/><font color=\"rgb(0,155,225)\">https://discord.gg/vfkD5VCRKU</font><br/><br/>Latest updates include major performance improvements, new gacha systems, and enhanced auto-farming features!",
  DelayToDestroy = 15,
  From = "ToZxart"
}
