return {
  Version = "1.18",
  News = {
    "V 1.18 - 10/25/2025",
    "> Added Auto Farm (Mobs) with mob selection - eliminates enemies without moving",
    "> Added Auto Farm (Boss Cave) with automatic reward collection",
    "> Added Auto Rebirth feature",
    "> Added Auto Claim Rewards",
    "> Added Auto Buy (Shop)",
    "> Added Auto Upgrade (Weapon)",
    "> Added Auto Upgrade (Forest)",
    "> Added Auto Hatch Eggs - automatically selects lucky eggs when available",
    "> Fixed farming resumption after Boss Cave completion",
    "> Auto Hatch now pauses when entering Boss Cave",
    "V 1.17 - 10/14/2025",
    "> Added AutoCraft tab with comprehensive crafting automation",
    "> Added Golden/Toxic/Galaxy pet auto-crafting with toggles, min amount, and delay controls",
    "> Added one-time craft buttons for Golden/Toxic/Galaxy pets with progress/status tracking",
    "> Added Mega/Ultra Potion crafting (auto toggles, amount/delay, craft buttons)",
    "> Added Luck Smoothie crafting (auto toggle, amount/delay, craft button)",
    "> Added Lunar Forge (Meteorite Fragments): auto sequential upgrades with delay control",
    "> Added Lunar Forge: craft specific recipe by ID and list all fragments",
    "> Fixed auto dungeon and auto mine conflict - they now work simultaneously",
    "> Added new modes for dungeon automation",
    "> Added Inventory tab with multiple auto-use sections",
    "> Added Regular/Mega/Ultra Potion auto-use (toggles, delays, one-time buttons)",
    "> Added Regular/Golden Fruit auto-eat (toggles, delays, one-time buttons)",
    "> Added Ancient Wheel auto-spin (toggle, delay, one-time button)",
    "> Added Aura Dice auto-roll (toggle, delay, one-time button)",
    "V 1.16 - 10/07/2025",
    "> Fixed auto mine issues",
    "> Updated auto mine: when teleport is selected, it now uses Tween teleport (the old teleport was detected by the game, causing errors over time)",
    "> Added Tween service for smoother movement",
    "> Introduced 'Ores per Room' — select how many ores to farm before moving to the next room",
    "> Added ore timeout setting",
    "> Added customizable auto speed — adjust MoveTo speed from the main tab for both Tween and MoveTo modes",
    "> Added auto rebirth feature",
    "> Reworked auto dungeon system",
    "V 1.15 - 9/16/2025",
    "> Resolved game GUI not opening bug.",
    "> Fixed auto tree feature.",
    "> :star: Fixed auto collect falling stars.",
    "> Fixed auto hatch issue for season events.",
    "> Fixed Auto Mining.",
    "V 1.14 - 9/16/2025",
    "> Added Auto Farm Metero.",
    "> Added Auto Buy Merchant.",
    "> Added Auto Collect Orbs feature.",
    "> Added Auto Collect Falling Stars.",
    "> Complete integration achieved between all automation systems (Auto Mine, Auto Metero, Auto Dungeon, and Auto Tree).",
    "> Please report any bugs through our Discord server. Additional features in development.",
  },
  Title = "The Intruders",
  MainText = "Make Sure to join our <b>Discord Server</b>.<br/><font color=\"rgb(0,155,225)\">https://discord.gg/vfkD5VCRKU</font><br/><br/>Latest updates include major performance improvements, new gacha systems, and enhanced auto-farming features!",
  DelayToDestroy = 15,
  From = "ToZxart"
}
